server:
  port: 8081
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/graphql_table
    password: prasad@8767
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
